name: devcontainer
author: Vladimir Silyaev
description: Setup devcontainer on ubuntu GitHub runner
inputs:
  name:
    description: "Name of container saved in the repository, default 'devcontainer'"
    required: false
    default: 'devcontainer'
  registry:
    description: 'Server address of Docker registry. If not set then will default to Docker Hub'
    required: false
    default: 'ghcr.io'
  username:
    description: 'Username used to log against the Docker registry'
    required: true
  password:
    description: 'Password or personal access token used to log against the Docker registry'
    required: true

outputs:
  exec:
    description: 'prefix that should be inserted to run commands in the container'
    value: ${{ steps.setup.outputs.exec }}

runs:
  using: "composite"
  steps:
    - name: devcontainer setup
      shell: bash
      id: setup
      run: |
        echo "::group::cache"
        npm install -g @devcontainers/cli
        IMAGE_ID=${{ inputs.registry }}/$GITHUB_REPOSITORY/${{ inputs.name }}
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        TAG="$GITHUB_REF_NAME"
        TAG=$(echo $TAG | tr '[A-Z].' '[a-z]_')
        old_id=''
        if docker pull $IMAGE_ID:$TAG; then
          old_id=$(docker image inspect $IMAGE_ID:$TAG --format "{{.ID}}")
        fi
        echo "::group::build"
        env BUILDKIT_PROGRESS=plain devcontainer build --image-name $IMAGE_ID --cache-from $IMAGE_ID:$TAG --workspace-folder .
        echo "::group::up"
        env BUILDKIT_PROGRESS=plain devcontainer up --workspace-folder .
        echo "EXEC=devcontainer exec --workspace-folder ." >> $GITHUB_OUTPUT
        echo "::group::push"
        if [ -n '${{ inputs.password }}' ]; then
          new_id=$(docker image inspect $IMAGE_ID --format "{{.ID}}")
          if docker tag $IMAGE_ID $IMAGE_ID:$TAG ; then
            if [ "$old_id" != "$new_id" ]; then
              username='${{ inputs.username }}'
              echo '${{ inputs.password }}' | docker login ${{ inputs.registry }} -u ${username:-'${{ github.actor }}'} --password-stdin
              if docker push $IMAGE_ID:$TAG ; then
                echo "::info :: pushed $IMAGE_ID:$TAG"
              else
                echo "::warning :: can't push $IMAGE_ID:$TAG"
              fi
              docker logout ${{ inputs.registry }}
            fi
          fi
        fi
